import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import navig from  "@/navig.json"
import {  randomUUID } from "crypto";
import Button from "@/components/Button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{console.log(navig)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-12 bg-emerald-800 sticky top-0">
          <div className="container mx-auto px-4 h-full">
            <div className="flex justify-between items-center h-full">
              {/* <Logo /> */}
              <ul className="hidden md:flex gap-x-6 text-white">
                <li>
                  <Link href="/about">
                    <p>About Us</p>
                  </Link>
                </li>
                <li>
                  <Link href="/services">
                    <p>Services</p>
                  </Link>
                </li>
                <li>
                  <Link href="/contacts">
                    <p>Contacts</p>
                  </Link>
                </li>
              </ul>
              {/* <Button /> */}
            </div>
          </div>
        </div>
        <main className="flex flex-row">
        <div className="h-screen w-[15rem] bg-amber-500 pl-10">
            
{navig.navigation.map((nav) => <h1 key ={randomUUID} ><Link href={`docs/${nav}`}>{nav}</Link></h1>)}
   </div>



        {children}
        </main>
      </body>
    </html>
  );
}
